[package]
name = "sorter"
version = "0.1.0"
edition = "2021"
authors = ["Muhammad Usman"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.3", features = ["cargo"] }
eframe = "0.26.2"
rfd = "0.14.1"
